services:
  rest-api-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: andrewkwolek3/rest-api-server:main
    container_name: rest-api-server
    ports:
      - "8082:8082"
    restart: unless-stopped
